WIP - adding m3u support via command args.
wetfish/sync pull request #54
Opened 2020-06-18 19:52 UTC by Meleeman01

this is a better implementation of m3u support from a maintainment perspective, a user will pass in the argument --m3u when running node server.js. a command called playlist is there for conveniance. so the code can be run in m3u playlist mode. so far it converts the file to json as a list of objects containing, name duration, and filename. still need to implement extention checking which could be done in the contructor, but i think it would be better to use the existing architecture on this one.

2020-06-19 03:43 UTC, itsrachelfish commented on media-player.js
> +            this.playlist = fs.readdirSync('./public/media').filter(function(file) {
Why are you still reading the `public/media` folder for m3u files? 

The m3u file should be passed as an argument on the command line. For example:

`npm run server -- --m3u="path/to/playlist.m3u"`

Or running node directly:

`node server.js --m3u="path/to/playlist.m3u"`

Both of these examples should result in the same behavior, you just need the extra "--" when passing args through npm. Learn more: https://stackoverflow.com/questions/11580961/sending-command-line-arguments-to-npm-script/14404223#14404223

2020-06-19 03:48 UTC, itsrachelfish commented on media-player.js
> +        this.options = args[2];
It's not a good idea to rely on arguments being passed in a specific order. If we started adding more command line arguments in the future, `args[2]` could end up being something else besides `--m3u`. It would be more reliable to use an argument parsing library instead: https://www.npmjs.com/package/process.argv

2020-06-19 03:49 UTC, itsrachelfish commented on media-player.js
> +                let list = file.segments.map(function(i){
Avoid single letter variables, please

2020-06-19 03:51 UTC, itsrachelfish commented on media-player.js
> +            });
It would be more readable to have a separate function for parsing files which gets called in a loop, instead of this anonymous function.

2020-06-19 03:52 UTC, itsrachelfish commented on package.json
> +    "playlist": "node server.js --m3u"
This is unnecessary. You can pass arguments directly to the start command. https://stackoverflow.com/questions/11580961/sending-command-line-arguments-to-npm-script/14404223#14404223

2020-06-19 04:11 UTC, kelsh commented on media-player.js
> +    //console.log(parsedFile);
remove commented out line

2020-06-19 04:13 UTC, kelsh commented on media-player.js
> +    url = fs.readFileSync(url).toString();
don't use the same variable name as a param.  Sometimes it makes sense, but in this case don't use a variable that you're also transforming.

2020-06-19 04:18 UTC, kelsh commented on media-player.js
> +    let parser = new m3uParser.Parser();
const

2020-06-19 04:19 UTC, kelsh commented on media-player.js
> +    let parsedFile = parser.manifest;
const or just return it here

2020-06-19 04:24 UTC, kelsh commented on media-player.js
> +        this.options = args[2];
in this case options is also not very descriptive.  playlist type or something

2020-06-19 04:26 UTC, kelsh commented on media-player.js
>          this.playlistCount = 0;
not sure everyone would agree with this, but your constructor should set the properties, and then even self initialize or the code below should be inside a 'start' command so you'd use it like new MediaPlayer(opts).start()

2020-06-19 04:27 UTC, kelsh commented on media-player.js
> +            this.playlist = fs.readdirSync('./public/media').filter(function(file) {
please initialize this.playlist in the constructor

2020-06-19 04:28 UTC, kelsh commented on media-player.js
> +                file = importM3U('./public/media/'+file);
same as comment above, try not to use parameter names as variable names

2020-06-19 04:34 UTC, kelsh commented on media-player.js
> +                let list = file.segments.map(function(i){
what is a file segment? it has a uri a name and a duration, so chunk probably isn't the right variable here, but please answer my question with your variable name.

2020-06-19 04:34 UTC, kelsh commented on media-player.js
> +                        if (i.uri) {
combine this and the one above it please.   Throw errors immediately if those things don't exist, then do the code below.

2020-06-19 04:34 UTC, kelsh commented on media-player.js
> +                            i.uri = i.uri.replace(/[\"\']/g,"");
same as before, make new vars, like 'santizedUri'

2020-06-19 04:36 UTC, kelsh commented on media-player.js
> +                        throw Error(`Weird. Somehow one of your files is missing a path`);
move this, don't make pyramid code

2020-06-19 04:37 UTC, kelsh commented on media-player.js
> +            this.playlist = this.playlist.flat();
same as before, don't assign this.playlist above to the class if the values are gonna be bad until they're flattened, make it a variable

2020-06-19 04:37 UTC, kelsh commented on media-player.js
> +            //console.log(this.playlist);
remove

2020-06-19 04:37 UTC, kelsh commented on media-player.js
> +            console.log(false);
remove

2020-06-19 04:37 UTC, kelsh commented on media-player.js
> +        //console.log(this.options);
remove

2020-06-19 04:39 UTC, kelsh commented on media-player.js
>  const playlistUrl = process.env.URL || 'http://localhost:3000';
you already saw the problem with this.  Please bounds check, and have dev url be in a config, not a catch

2020-06-19 04:40 UTC, kelsh commented on media-player.js
>  let path = require('path');
these are all consts except maybe count i guess

2020-06-19 04:40 UTC, kelsh commented on media-player.js
> +    let parser = new m3uParser.Parser();
const

2020-06-19 04:40 UTC, kelsh commented on media-player.js
> +            console.log(true);
remove

2020-06-19 04:44 UTC, kelsh commented on media-player.js
> +            this.playlist = fs.readdirSync('./public/media').filter(function(file) {
remove console.lolg

2020-06-19 04:56 UTC, Meleeman01 commented on media-player.js
> +                let list = file.segments.map(function(i){
so the m3u parser will return a json string and the relevant information which is segments will display duration, uri, and timeline, which it parses this -> #ext:12, /path/to/file.mp4 into this
`segments: {
{object containing uri timeline and duration},
{object containing uri timeline and duration}
}`

2020-06-19 04:56 UTC, Meleeman01 commented on media-player.js
> +    //console.log(parsedFile);
i will eventually lolol

2020-06-19 04:58 UTC, Meleeman01 commented on media-player.js
> +    url = fs.readFileSync(url).toString();
yeah, i copy and pasted this function and didn't bother to name it differently lol, i'll be sure to change it to something more meaningful in the next iteration.

2020-06-19 05:03 UTC, Meleeman01 commented on media-player.js
> +                file = importM3U('./public/media/'+file);
there could be multiple m3u files in the media folder, and each file would need to be imported. however according to rachel, i need to pass in a path to a single m3u playlist. this will probably be removed anyway. i don't see why mutating the file directly is a bad idea, map will return a new array anyway so i'm not mutating the array directly

2020-06-19 05:07 UTC, Meleeman01 commented on media-player.js
> +                        if (i.uri) {
i think this things should be checked individually because a user should know specifically what the errors are, and combining them in the if statement you would not be able to differentiate between a missing uri or a missing duration.

2020-06-19 05:13 UTC, Meleeman01 commented on media-player.js
>  const playlistUrl = process.env.URL || 'http://localhost:3000';
i don't recall the problem with this, and what is a bounds check? and there is a config in the project.

2020-06-19 18:29 UTC, kelsh commented on media-player.js
>  const playlistUrl = process.env.URL || 'http://localhost:3000';
the problem is there is no check if the url exists, and if the config exists, and if it doesn't, the program runs anyways.

2020-06-20 05:54 UTC, Meleeman01 commented on media-player.js
> +                        throw Error(`Weird. Somehow one of your files is missing a path`);
pyramid code sounds kinda cool, why would i want to move it?

2020-06-20 09:47 UTC, itsrachelfish commented on media-player.js
> +        this.playlistType = argv;
...why are you setting the entire process arguments list as the playlistType?

2020-06-20 09:48 UTC, itsrachelfish commented on media-player.js
> +        if (this.playlistType.hasOwnProperty('m3u')) {
why not just use `if(argv.m3u) { ... }`?

2020-06-20 09:49 UTC, itsrachelfish commented on media-player.js
> +            this.playlist = importM3U(this.playlistType.m3u).map(this.processM3U).filter(this.isValidMediaFile);
Awesome!! This is way more readable now :slightly_smiling_face:

2020-06-20 09:51 UTC, itsrachelfish commented on media-player.js
> +                //remove quotes in filename if they exist.
what if a filename legit has quotes in it???

2020-06-21 07:17 UTC, Meleeman01 commented on media-player.js
> +        if (this.playlistType.hasOwnProperty('m3u')) {
I think that would be a more concise way to check for the m3u option and run diff code.

2020-06-21 07:32 UTC, kelsh commented on README.md
> +-in order to use an m3u file feature simply start sync like this 'npm run start -- --m3u=/path/to/playlist.m3u'
can you have multiple playlist types?  multiple playlists?

2020-07-09 10:41 UTC, Meleeman01 commented on README.md
> +-in order to use an m3u file feature simply start sync like this 'npm run start -- --m3u=/path/to/playlist.m3u'
you can have one playlist and it can be m3u or m3u8.

2020-09-27 18:36 UTC, itsrachelfish requested changes
A couple small changes, but besides that this looks good!

2020-09-27 18:36 UTC, itsrachelfish commented on media-player.js
> +        if (++this.filesProcessed === this.mediaLengths.length) {
This is a bit unclear. Why are you incrementing the files processed variable in an if statement? Imo you should always keep evaluation and comparison separate.

2020-09-27 18:36 UTC, itsrachelfish commented on package.json
> +    "playlist": "node server.js --m3u"
This playlist option should still be removed since we can now play any m3u file based on the command line args

2020-10-06 01:39 UTC, itsrachelfish requested changes
Found an edge case. Besides that this is working as expected :+1:

2020-10-06 01:39 UTC, itsrachelfish commented on media-player.js
> +                if (this.playlist[this.mediaIndex]['url'].includes('http')) {
This should probably actually parse the URL instead of just checking if the URL includes "http". What happens if you have a local media file with the string "http" in it? Like `How to set up a http server.mp4`

2020-10-06 01:39 UTC, itsrachelfish commented on media-player.js
> +                if (this.playlist[this.mediaIndex]['url'].includes('http')) {
Yep, I was able to confirm my hypothesis.  "http" is triggering the URL behavior regardless of where it occurs in the filename 

![http-filename-issue](https://user-images.githubusercontent.com/1670549/95149123-5e85e000-0742-11eb-92df-a6649b298a24.png)

2020-10-12 21:22 UTC, mozai commented
meleeman and I are testing today (Oct 12) and found something odd while testing on fishhost:
```
#EXTM3U
#EXTINF:33,vapourwave
http://[redacted]/temp/vapourwave.mp4
#EXTINF:58,PepeSilvia
/media/Pepe_Silvia.mp4
#EXTINF:25,ABC Monday Night Movie
https://[redacted]/tumblr_qhavdc9szN1ute1ez.mp4
```
If a client connects during the "PepeSilva" they get the proper url "https://fishhost/media/Pepe_Silvia.mp4" but if they join during "vapourwave" and the timer ticks down, over the websocket the client is told to go to "http://localhost:3000/media/Pepe_Silvia.mp4"

2020-10-19 05:32 UTC, Meleeman01 commented
have you tried using https://fishhost/ in the base url of the env file?

2020-10-19 07:54 UTC, Meleeman01 commented
> meleeman and I are testing today (Oct 12) and found something odd while testing on fishhost:
> 
> ```
> #EXTM3U
> #EXTINF:33,vapourwave
> http://[redacted]/temp/vapourwave.mp4
> #EXTINF:58,PepeSilvia
> /media/Pepe_Silvia.mp4
> #EXTINF:25,ABC Monday Night Movie
> https://[redacted]/tumblr_qhavdc9szN1ute1ez.mp4
> ```
> 
> If a client connects during the "PepeSilva" they get the proper url "https://fishhost/media/Pepe_Silvia.mp4" but if they join during "vapourwave" and the timer ticks down, over the websocket the client is told to go to "http://localhost:3000/media/Pepe_Silvia.mp4"
> 
> WORKAROUND: always use absolute URLs, not relative paths, even for locally-hosted files.

so whats happening is that the m3u file is specified too long for the content in some cases mainly #EXTINF:12,Faec
https://va.media.tumblr.com/tumblr_qi3r87aTGJ1tfmrz4.mp4  and because of that it will pause the media, and when the newMedia event happens, the current implementation will keep it paused and it while socket.io sets the flag for vueapp.js it doesn't actually make it to vueapp.js. so the solution here is to properly time your files slightly under, and fix the way files are handled when newMedia Event happens on pause, so the new file should play all the time when in m3u mode i think unless the user has explictly pressed the pause button. alternatively, i could just reflect this in the UI so a user will intinctively press it and it will play the media as I've observed.

2020-11-26 10:29 UTC, itsrachelfish approved these changes

2020-11-26 10:29 UTC, itsrachelfish commented
I suppose we can merge this now since we are already using this code on production

2020-11-26 10:29 UTC, merged